In [1]:
import pandas as pd

/var/folders/8p/ft1k5gt143qc3r7v0q4q31dm0000gn/T/ipykernel_2298/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [15]:
data = pd.read_csv('wine_cleared.csv')

In [14]:
country_population = pd.read_csv('country_population.csv', sep=';')
country_population.head(30)

           country     population
0            China  1,411,778,724
1            India  1,386,584,581
2               US    333,022,386
3        Indonesia    271,350,000
4         Pakistan    225,200,000
5           Brazil    214,191,924
6          Nigeria    211,401,000
7       Bangladesh    172,011,942
8           Russia    146,171,015
9           Mexico    126,014,024
10           Japan    125,470,000
11        Ethiopia    117,876,000
12     Philippines    111,335,110
13           Egypt    102,785,900
14         Vietnam     98,510,000
15        DR Congo     92,378,000
16            Iran     85,096,209
17          Turkey     83,614,362
18         Germany     83,129,285
19          France     68,035,000
20  United Kingdom     67,081,234
21        Thailand     66,739,317
22    South Africa     60,142,978
23        Tanzania     59,441,988
24           Italy     59,097,904
25         Myanmar     55,294,979
26     South Korea     51,671,569
27        Colombia     51,049,498
28           Kenya     47,564,296
29           Spain     47,394,223

In [16]:
data.join(country_population.set_index('country'), on='country')

,Unnamed: 0,country,description,designation,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery,population
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,35.363389,Sicily & Sardinia,Etna,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,"59,097,904"
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.000000,Douro,unknown,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,"10,347,892"
2,2,US,"Tart and snappy, the flavors of lime flesh and...",unknown,87,14.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,"333,022,386"
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.000000,Michigan,Lake Michigan Shore,Alexander Peartree,unknown,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,"333,022,386"
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.000000,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,"333,022,386"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.000000,Mosel,unknown,Anna Lee C. Iijima,unknown,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),"83,129,285"
129967,129967,US,Citation is given as much as a decade of bottl...,unknown,90,75.000000,Oregon,Oregon,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,"333,022,386"
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,"68,035,000"
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",unknown,90,32.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,"68,035,000"
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.000000,Alsace,Alsace,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,"68,035,000"

In [20]:
country_area = pd.read_csv('country_area.csv', sep=';')
country_area.head()

  country        area
0  Russia  17075400.0
1  Canada   9984670.0
2   China   9596960.0
3      US   9372610.0
4  Brazil   8547000.0